package com.mateuszkrawczuk.tvprogramsearcher.common.repository

import com.mateuszkrawczuk.TvProgramSearcher.common.di.IDatabaseDependencyProvider
import com.mateuszkrawczuk.tvprogramsearcher.db.TvProgramSearcherDatabase

expect fun createDb(dependencyProvider: IDatabaseDependencyProvider) : TvProgramSearcherDatabase?
